### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/flappy-astronaut#1]
Hi @LornaLynch,

I've still got to add images to this one, but could you start a copy edit on the text for me please.

kthxbye

**Comment by LornaLynch** [comment]
Will do.

**Comment by MarcScott** [comment]
Can I close this @LornaLynch or is there still edits to be done
Thanks

**Comment by LornaLynch** [comment]
I'm just doing a final check now: I'll close it when I'm done :)

**Comment by LornaLynch** [comment]
I think we're done.

**Comment by MarcScott** [comment]
Awesome - thankyou
