### ISSUE TITLE
Typo in "Splitting the columns." trinket. 

### ISSUE THREAD

**Issue by alexaverill** [raspberrypilearning/flappy-astronaut#4]
There is a type in the trinket file for the Splitting the Columns section of this worksheet. 

https://trinket.io/embed/python/27f336c50d 

On line three is has: `from random import randing`
It should read: `from random import randint`

I didn't see a way to submit a pull request that would fix the issue otherwise I would have.

Thanks!

**Comment by lawsie** [comment]
Thanks @alexaverill.

@MarcScott please could you fix this on the trinket?

**Comment by MarcScott** [comment]
Sorted - cheers
